### ISSUE TITLE
Giant error dump

### ISSUE THREAD

**Issue by zephiowl** [vincentmathis/osu-beatmap-downloader#9]
Hey so I just tried using this for the first time but every time I try I get this giant dump of an error message; I cant really make sense of it so if I could get some help that'd be great!

```Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\pikac\AppData\Local\osu!\Songs> osu-beatmap-downloader download
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\pikac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\osu-beatmap-downloader.exe\__main__.py", line 4, in <module>
  File "C:\Users\pikac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\osu_beatmap_downloader\__init__.py", line 1, in <module>
    from .downloader import main
  File "C:\Users\pikac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\osu_beatmap_downloader\downloader.py", line 10, in <module>
    from PyInquirer import prompt
  File "C:\Users\pikac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\PyInquirer\__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "C:\Users\pikac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "C:\Users\pikac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "C:\Users\pikac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "C:\Users\pikac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\key_binding\bindings\basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "C:\Users\pikac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "C:\Users\pikac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\styles\__init__.py", line 8, in <module>
    from .from_dict import *
  File "C:\Users\pikac\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\prompt_toolkit\styles\from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\collections\__init__.py)
PS C:\Users\pikac\AppData\Local\osu!\Songs>

**Comment by vincentmathis** [comment]
The error was because the dependency PyInquirer hasn't been updated in 4 years and was incompatible with python 3.10. I switched to InquirerPy and fixed another error stemming from a change in Osu website.

Can you try reinstalling osu-beatmap-downloader with pip and report back if it works?

**Comment by zephiowl** [comment]
```PS C:\Users\pikac> pip install osu-beatmap-downloader
Collecting osu-beatmap-downloader
  Downloading osu_beatmap_downloader-0.1.7-py3-none-any.whl (18 kB)
Requirement already satisfied: loguru<0.5.0,>=0.4.1 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from osu-beatmap-downloader) (0.4.1)
Collecting inquirerpy<0.4.0,>=0.3.3
  Downloading InquirerPy-0.3.3-py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 KB 1.2 MB/s eta 0:00:00
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from osu-beatmap-downloader) (2.26.0)
Collecting prompt-toolkit<4.0.0,>=3.0.1
  Downloading prompt_toolkit-3.0.28-py3-none-any.whl (380 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.2/380.2 KB 2.2 MB/s eta 0:00:00
Collecting pfzy<0.4.0,>=0.3.1
  Downloading pfzy-0.3.4-py3-none-any.whl (8.5 kB)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from loguru<0.5.0,>=0.4.1->osu-beatmap-downloader) (1.1.0)
Requirement already satisfied: colorama>=0.3.4 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from loguru<0.5.0,>=0.4.1->osu-beatmap-downloader) (0.4.4)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3.0.0,>=2.23.0->osu-beatmap-downloader) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3.0.0,>=2.23.0->osu-beatmap-downloader) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3.0.0,>=2.23.0->osu-beatmap-downloader) (1.26.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3.0.0,>=2.23.0->osu-beatmap-downloader) (3.3)
Requirement already satisfied: wcwidth in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from prompt-toolkit<4.0.0,>=3.0.1->inquirerpy<0.4.0,>=0.3.3->osu-beatmap-downloader) (0.2.5)
Installing collected packages: prompt-toolkit, pfzy, inquirerpy, osu-beatmap-downloader
  Attempting uninstall: prompt-toolkit
    Found existing installation: prompt-toolkit 1.0.14
    Uninstalling prompt-toolkit-1.0.14:
      Successfully uninstalled prompt-toolkit-1.0.14
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyinquirer 1.0.3 requires prompt_toolkit==1.0.14, but you have prompt-toolkit 3.0.28 which is incompatible.
Successfully installed inquirerpy-0.3.3 osu-beatmap-downloader-0.1.7 pfzy-0.3.4 prompt-toolkit-3.0.28
PS C:\Users\pikac>

**Comment by vincentmathis** [comment]
I weirdly had the same error, can you try reinstalling again and see if it persists?

**Comment by zephiowl** [comment]
```PS C:\Users\pikac> pip uninstall osu-beatmap-downloader
Found existing installation: osu-beatmap-downloader 0.1.7
Uninstalling osu-beatmap-downloader-0.1.7:
  Would remove:
    c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\scripts\osu-beatmap-downloader.exe
    c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages\osu_beatmap_downloader-0.1.7.dist-info\*
    c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages\osu_beatmap_downloader\*
Proceed (Y/n)? y
  Successfully uninstalled osu-beatmap-downloader-0.1.7
PS C:\Users\pikac> pip install osu-beatmap-downloader
Collecting osu-beatmap-downloader
  Using cached osu_beatmap_downloader-0.1.7-py3-none-any.whl (18 kB)
Requirement already satisfied: loguru<0.5.0,>=0.4.1 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from osu-beatmap-downloader) (0.4.1)
Requirement already satisfied: inquirerpy<0.4.0,>=0.3.3 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from osu-beatmap-downloader) (0.3.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from osu-beatmap-downloader) (2.26.0)
Requirement already satisfied: prompt-toolkit<4.0.0,>=3.0.1 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from inquirerpy<0.4.0,>=0.3.3->osu-beatmap-downloader) (3.0.28)
Requirement already satisfied: pfzy<0.4.0,>=0.3.1 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from inquirerpy<0.4.0,>=0.3.3->osu-beatmap-downloader) (0.3.4)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from loguru<0.5.0,>=0.4.1->osu-beatmap-downloader) (1.1.0)
Requirement already satisfied: colorama>=0.3.4 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from loguru<0.5.0,>=0.4.1->osu-beatmap-downloader) (0.4.4)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3.0.0,>=2.23.0->osu-beatmap-downloader) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3.0.0,>=2.23.0->osu-beatmap-downloader) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3.0.0,>=2.23.0->osu-beatmap-downloader) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from requests<3.0.0,>=2.23.0->osu-beatmap-downloader) (1.26.6)
Requirement already satisfied: wcwidth in c:\users\pikac\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from prompt-toolkit<4.0.0,>=3.0.1->inquirerpy<0.4.0,>=0.3.3->osu-beatmap-downloader) (0.2.5)
Installing collected packages: osu-beatmap-downloader
Successfully installed osu-beatmap-downloader-0.1.7
PS C:\Users\pikac>

**Comment by vincentmathis** [comment]
Looks good now, go to your osu song folder and run it

**Comment by zephiowl** [comment]
Aye it works now; thank you so much man I was struggling to figure it out for like an hour or so.
